routes/web.php
<?php


/*
 * Admin Routes
 */
Route::prefix('admin')->group(function() {

    Route::middleware('auth:admin')->group(function() {
        // Dashboard
        Route::get('/', 'DashboardController@index')->name('admin');

        // Products
        Route::resource('/products','ProductController');

        // Orders
        Route::resource('/orders','OrderController');
        Route::get('/confirm/{id}','OrderController@confirm')->name('order.confirm');
        Route::get('/pending/{id}','OrderController@pending')->name('order.pending');

        // Users
        Route::resource('/users','UsersController');

        // Logout
        Route::get('/logout','AdminUserController@logout');

        Route::get('/parse','ParseXMLController@parse')->name('parse.view');
        Route::post('/update','ParseXMLController@parseXML')->name('parseXML');

        Route::post('/action','ProductController@actionCreate');
        Route::get('/search','ProductController@search')->name('admin/search');
        Route::get('/category/{id}','ProductController@category')->name('admin/category');
        Route::get('/actions','ProductController@actions');
        Route::delete('actions/destroy/{product_id}','ProductController@deleteAction')->name('admin.action');
        Route::post('/bestseller/{code}','BestsellerController@makeBestsellers')->name('makeBestseller');
        Route::get('/bestsellers','BestsellerController@getBestsellers')->name('getBestsellers');
        Route::delete('bestsellers/{code}','BestsellerController@removeFromBestsellers')->name('bestseller.destroy');
        Route::get('banners','BannersController@index');
        Route::post('addBanner','BannersController@addBanner');



    });

    // Admin Login
    Route::get('/login', 'AdminUserController@index');
    Route::post('/login', 'AdminUserController@store');
});

/*
 * Front Routes
 */

Route::get('/', 'Front\HomeController@index');
Route::get('/category/{id}','Front\HomeController@category')->name('category');
Route::get('/search','Front\HomeController@search')->name('search');
Route::get('/onaction','Front\HomeController@onaction')->name('onaction');


// User Registration
Route::get('/user/register','Front\RegistrationController@index');
Route::post('/user/register','Front\RegistrationController@store');

// User Login
Route::get('/user/login','Front\SessionsController@index');
Route::post('/user/login','Front\SessionsController@store');

// Logout
Route::get('/user/logout','Front\SessionsController@logout');

Route::get('/user/profile', 'Front\UserProfileController@index');
Route::get('/user/order/{id}','Front\UserProfileController@show');

// Cart
Route::get('/cart', 'Front\CartController@index');
Route::post('/cart','Front\CartController@store')->name('cart');
Route::patch('/cart/update/{product}','Front\CartController@update')->name('cart.update');
Route::delete('/cart/remove/{product}','Front\CartController@destroy')->name('cart.destroy');
Route::post('/cart/saveLater/{product}', 'Front\CartController@saveLater')->name('cart.saveLater');


// Save for later
Route::delete('/saveLater/destroy/{product}','Front\SaveLaterController@destroy')->name('saveLater.destroy');
Route::post('/cart/moveToCart/{product}','Front\SaveLaterController@moveToCart')->name('moveToCart');

// Checkout
Route::get('/checkout','Front\CheckoutController@index');
Route::post('/checkout','Front\CheckoutController@store')->name('checkout');

Route::get('empty', function() {
    Cart::instance('default')->destroy();
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function order() {
        return $this->hasMany(Order::class);
    }

}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;
use App\User;
use App\Order;
use Illuminate\Http\Request;

class UsersController extends Controller
{

    public function index() {
        $users = User::all();
        return view('admin.users.index', compact('users'));
    }

    public function show($id) {

        // Find the user
        $orders = Order::where('user_id', $id)->get();

        // Return array back to user details page

        return view('admin.users.details', compact('orders'));

    }
}

resources/views/admin/users/details.blade.php
@extends('admin.layouts.master')

@section('page')
    Detalji o porudzini
@endsection

@section('content')

    <div class="row">

        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">{{ $orders[0]->user->name }} Detalji o porudzini</h4>
                    <p class="category">Lista registrovanih korisnika</p>
                </div>
                <div class="content table-responsive table-full-width">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>ID porudzbine</th>
                            <th>Ime proizvoda</th>
                            <th>Kolicina</th>
                            <th>Ukupna cena</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($orders as $order)
                            <tr>

                                <td>{{ $order->id }}</td>

                                <td>
                                    @foreach ($order->products as $item)
                                        <table class="table">
                                            <tr>
                                                <td>{{ $item->name }}</td>
                                            </tr>
                                        </table>
                                    @endforeach
                                </td>

                                <td>
                                    @foreach ($order->orderItems as $item)
                                        <table class="table">
                                            <tr>
                                                <td>{{ $item->quantity }}</td>
                                            </tr>
                                        </table>
                                    @endforeach
                                </td>

                                <td>
                                    @foreach ($order->orderItems as $item)
                                        <table class="table">
                                            <tr>
                                                <td>{{ $item->price }} din.</td>
                                            </tr>
                                        </table>
                                    @endforeach
                                </td>


                                <td>
                                    @if($order->status)
                                        <span class="label label-success">Potvrdjeno</span>
                                    @else
                                        <span class="label label-warning">Na cekanju</span>
                                    @endif
                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.master')

@section('page')
    Users
@endsection

@section('content')

    <div class="row">

        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Korisnici</h4>
                    <p class="category">Lista registrovanih korisnika</p>
                </div>
                <div class="content table-responsive table-full-width">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Ime i prezime</th>
                            <th>Email</th>
                            <th>Datum registracije</th>
                            <th>Akcije</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $user)

                            <tr>

                                <td>{{ $user->id }}</td>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>{{ $user->created_at->diffForHumans() }}</td>
                                <td>

                                   {{ link_to_route('users.show', 'Detalji', $user->id, ['class'=>'btn btn-success btn-sm']) }}

                                </td>

                            </tr>
                        @endforeach

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>

@endsection