routes/web.php
<?php


/*
 * Admin Routes
 */
Route::prefix('admin')->group(function() {

    Route::middleware('auth:admin')->group(function() {
        // Dashboard
        Route::get('/', 'DashboardController@index')->name('admin');

        // Products
        Route::resource('/products','ProductController');

        // Orders
        Route::resource('/orders','OrderController');
        Route::get('/confirm/{id}','OrderController@confirm')->name('order.confirm');
        Route::get('/pending/{id}','OrderController@pending')->name('order.pending');

        // Users
        Route::resource('/users','UsersController');

        // Logout
        Route::get('/logout','AdminUserController@logout');

        Route::get('/parse','ParseXMLController@parse')->name('parse.view');
        Route::post('/update','ParseXMLController@parseXML')->name('parseXML');

        Route::post('/action','ProductController@actionCreate');
        Route::get('/search','ProductController@search')->name('admin/search');
        Route::get('/category/{id}','ProductController@category')->name('admin/category');
        Route::get('/actions','ProductController@actions');
        Route::delete('actions/destroy/{product_id}','ProductController@deleteAction')->name('admin.action');
        Route::post('/bestseller/{code}','BestsellerController@makeBestsellers')->name('makeBestseller');
        Route::get('/bestsellers','BestsellerController@getBestsellers')->name('getBestsellers');
        Route::delete('bestsellers/{code}','BestsellerController@removeFromBestsellers')->name('bestseller.destroy');
        Route::get('banners','BannersController@index');
        Route::post('addBanner','BannersController@addBanner');



    });

    // Admin Login
    Route::get('/login', 'AdminUserController@index');
    Route::post('/login', 'AdminUserController@store');
});

/*
 * Front Routes
 */

Route::get('/', 'Front\HomeController@index');
Route::get('/category/{id}','Front\HomeController@category')->name('category');
Route::get('/search','Front\HomeController@search')->name('search');
Route::get('/onaction','Front\HomeController@onaction')->name('onaction');


// User Registration
Route::get('/user/register','Front\RegistrationController@index');
Route::post('/user/register','Front\RegistrationController@store');

// User Login
Route::get('/user/login','Front\SessionsController@index');
Route::post('/user/login','Front\SessionsController@store');

// Logout
Route::get('/user/logout','Front\SessionsController@logout');

Route::get('/user/profile', 'Front\UserProfileController@index');
Route::get('/user/order/{id}','Front\UserProfileController@show');

// Cart
Route::get('/cart', 'Front\CartController@index');
Route::post('/cart','Front\CartController@store')->name('cart');
Route::patch('/cart/update/{product}','Front\CartController@update')->name('cart.update');
Route::delete('/cart/remove/{product}','Front\CartController@destroy')->name('cart.destroy');
Route::post('/cart/saveLater/{product}', 'Front\CartController@saveLater')->name('cart.saveLater');


// Save for later
Route::delete('/saveLater/destroy/{product}','Front\SaveLaterController@destroy')->name('saveLater.destroy');
Route::post('/cart/moveToCart/{product}','Front\SaveLaterController@moveToCart')->name('moveToCart');

// Checkout
Route::get('/checkout','Front\CheckoutController@index');
Route::post('/checkout','Front\CheckoutController@store')->name('checkout');

Route::get('empty', function() {
    Cart::instance('default')->destroy();
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{

    protected $guarded = [];

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function OrderItems() {
        return $this->hasMany(OrderItems::class);
    }

    public function products() {
        return $this->belongsToMany(Product::class,'order_items');
    }


}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    public function index() {
        $orders = Order::all();

        return view('admin.orders.index', compact('orders'));
    }


    public function confirm($id) {

        // Find the order
        $order = Order::find($id);

        // Update the Order
        $order->update(['status' => 1]);

        // Session message
        session()->flash('msg','Order has been confirmed');

        // Redirect the page
        return redirect('admin/orders');


    }


    public function pending($id){

        // Find the order
        $order = Order::find($id);

        // Update the order status

        $order->update(['status' => 0]);

        // Session Message
        session()->flash('msg','Order has been again into pending');

        // Redirect the page
        return redirect('admin/orders');

    }

    public function show($id) {

        $order = Order::find($id);

        return view('admin.orders.details', compact('order'));
    }

}

resources/views/admin/orders/details.blade.php
@extends('admin.layouts.master')

@section('page')
    Detalji porudzbine
@endsection


@section('content')

    <div class="row">

        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Detalji porudzbine</h4>
                    <p class="category">Detalji porudzbine</p>
                </div>
                <div class="content table-responsive table-full-width">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Datum</th>
                            <th>Adresa</th>
                            <th>Telefon</th>
                            <th>Status</th>
                            <th>Akcija</th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ $order->id }}</td>
                                <td>{{ $order->date }}</td>
                                <td>{{ $order->address }}</td>
                                <td>{{ $order->phone }}</td>

                                <td>
                                    @if ($order->status)
                                        <span class="label label-success">Potvrdjena</span>
                                    @else
                                        <span class="label label-warning">Cekanje</span>
                                    @endif
                                </td>
                                <td>
                                    @if ($order->status)
                                    {{ link_to_route('order.pending','Cekanje', $order->id, ['class'=>'btn btn-warning btn-sm']) }}
                                @else
                                    {{ link_to_route('order.confirm','Potvrdi', $order->id, ['class'=>'btn btn-success btn-sm']) }}
                                @endif  </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-6">

        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Detalji o artiklu</h4>
                    <p class="category">Detalji o artiklu</p>
                </div>
                <div class="content table-responsive table-full-width">
                    <table class="table table-striped">
                        <tr>
                            <th>ID porudzbine</th>
                            <th>Ime proizvoda</th>
                            <th>Cena</th>
                            <th>Kolicina</th>
                            <th>Slika</th>
                        </tr>
                        <tr>
                            <td>{{ $order->id }}</td>
                            <td>
                                @foreach ($order->products as $product)
                                    <table class="table">
                                        <tr>
                                            <td>{{ $product->name }}</td>
                                        </tr>
                                    </table>
                                @endforeach
                            </td>

                            <td>
                                @foreach ($order->orderItems as $item)
                                    <table class="table">
                                        <tr>
                                            <td>{{ $item->price }}</td>
                                        </tr>
                                    </table>
                                @endforeach
                            </td>
                            <td>
                                @foreach ($order->orderItems as $item)
                                    <table class="table">
                                        <tr>
                                            <td>{{ $item->quantity }}</td>
                                        </tr>
                                    </table>
                                @endforeach
                            </td>
                            <td>
                                @foreach ($order->products as $product)
                                    <table class="table">
                                        <tr>
                                            @if(json_decode($product->images  !== null))
                                                @foreach(json_decode($product->images) as $image => $value)
                                                    @if(is_array($value))
                                                        <td><img  src="{{$value[0]}}" style="width: 5em"></td>
                                                    @else
                                                        <td><img  src="{{$value}}" style="width: 5em"></td>
                                                    @endif
                                                @endforeach
                                            @endif
                                        </tr>
                                    </table>
                                @endforeach
                            </td>
                        </tr>

                    </table>

                </div>
            </div>
        </div>
    </div>

    <a href="{{ url('/admin/orders') }}" class="btn btn-success">Nazad na porudzbine</a>
    
@endsection

resources/views/admin/orders/index.blade.php
@extends('admin.layouts.master')

@section('page')
    Porudzbine
@endsection

@section('content')
    <div class="row">

        <div class="col-md-12">

            @include('admin.layouts.message')

            <div class="card">
                <div class="header">
                    <h4 class="title">Porudzbine</h4>
                    <p class="category">Lista porudzbina</p>
                </div>
                <div class="content table-responsive table-full-width">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Korisnik</th>
                            <th>Sifra</th>
                            <th>Artikal</th>
                            <th>Kolicina</th>
                            <th>Status</th>
                            <th>Akcija</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            @foreach ($orders as $order)
                                <td>{{ $order->id }}</td>
                                <td>{{ $order->name }}</td>

                                <td>
                                @foreach ($order->products as $item)
                                    <table class="table">
                                        <tr>
                                            <td>{{$item->code}} </td>
                                            <td>{{ $item->name }}</td>

                                        </tr>
                                    </table>
                                    @endforeach
                                </td>

                                <td>
                                    @foreach ($order->orderItems as $item)
                                        <table class="table">
                                            <tr>
                                                <td>{{ $item->quantity }}</td>
                                            </tr>
                                        </table>
                                    @endforeach
                                </td>

                                <td>
                                    @if ($order->status)
                                        <span class="label label-success">Potvrdjena</span>
                                    @else
                                        <span class="label label-warning">Cekanje</span>
                                    @endif
                                </td>

                            <td>

                                @if ($order->status)
                                    {{ link_to_route('order.pending','Cekanje', $order->id, ['class'=>'btn btn-warning btn-sm']) }}
                                @else
                                    {{ link_to_route('order.confirm','Potvrdi', $order->id, ['class'=>'btn btn-success btn-sm']) }}
                                @endif

                                {{ link_to_route('orders.show','Detalji', $order->id, ['class'=>'btn btn-success btn-sm']) }}

                            </td>
                        </tr>
                        @endforeach



                        </tbody>
                    </table>

                </div>
            </div>
        </div>


    </div>
@endsection