routes/web.php
<?php


/*
 * Admin Routes
 */
Route::prefix('admin')->group(function() {

    Route::middleware('auth:admin')->group(function() {
        // Dashboard
        Route::get('/', 'DashboardController@index')->name('admin');

        // Products
        Route::resource('/products','ProductController');

        // Orders
        Route::resource('/orders','OrderController');
        Route::get('/confirm/{id}','OrderController@confirm')->name('order.confirm');
        Route::get('/pending/{id}','OrderController@pending')->name('order.pending');

        // Users
        Route::resource('/users','UsersController');

        // Logout
        Route::get('/logout','AdminUserController@logout');

        Route::get('/parse','ParseXMLController@parse')->name('parse.view');
        Route::post('/update','ParseXMLController@parseXML')->name('parseXML');

        Route::post('/action','ProductController@actionCreate');
        Route::get('/search','ProductController@search')->name('admin/search');
        Route::get('/category/{id}','ProductController@category')->name('admin/category');
        Route::get('/actions','ProductController@actions');
        Route::delete('actions/destroy/{product_id}','ProductController@deleteAction')->name('admin.action');
        Route::post('/bestseller/{code}','BestsellerController@makeBestsellers')->name('makeBestseller');
        Route::get('/bestsellers','BestsellerController@getBestsellers')->name('getBestsellers');
        Route::delete('bestsellers/{code}','BestsellerController@removeFromBestsellers')->name('bestseller.destroy');
        Route::get('banners','BannersController@index');
        Route::post('addBanner','BannersController@addBanner');



    });

    // Admin Login
    Route::get('/login', 'AdminUserController@index');
    Route::post('/login', 'AdminUserController@store');
});

/*
 * Front Routes
 */

Route::get('/', 'Front\HomeController@index');
Route::get('/category/{id}','Front\HomeController@category')->name('category');
Route::get('/search','Front\HomeController@search')->name('search');
Route::get('/onaction','Front\HomeController@onaction')->name('onaction');


// User Registration
Route::get('/user/register','Front\RegistrationController@index');
Route::post('/user/register','Front\RegistrationController@store');

// User Login
Route::get('/user/login','Front\SessionsController@index');
Route::post('/user/login','Front\SessionsController@store');

// Logout
Route::get('/user/logout','Front\SessionsController@logout');

Route::get('/user/profile', 'Front\UserProfileController@index');
Route::get('/user/order/{id}','Front\UserProfileController@show');

// Cart
Route::get('/cart', 'Front\CartController@index');
Route::post('/cart','Front\CartController@store')->name('cart');
Route::patch('/cart/update/{product}','Front\CartController@update')->name('cart.update');
Route::delete('/cart/remove/{product}','Front\CartController@destroy')->name('cart.destroy');
Route::post('/cart/saveLater/{product}', 'Front\CartController@saveLater')->name('cart.saveLater');


// Save for later
Route::delete('/saveLater/destroy/{product}','Front\SaveLaterController@destroy')->name('saveLater.destroy');
Route::post('/cart/moveToCart/{product}','Front\SaveLaterController@moveToCart')->name('moveToCart');

// Checkout
Route::get('/checkout','Front\CheckoutController@index');
Route::post('/checkout','Front\CheckoutController@store')->name('checkout');

Route::get('empty', function() {
    Cart::instance('default')->destroy();
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $guarded = [];

    protected $fillable = [
                'code',
                'category',
                'category1',
                'category2',
                'available',
                'name',
                'price',
                'description' ,
                'images'
    ];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Action;
use App\Category;
use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index() {

        $products = Product::paginate(18);
        $category = Category::with('childrenCategories')->get();
        $categories = [];
        foreach ($category as $cat){

            $categories[]= $cat;
        }


        return view('admin.products.index', compact('products','categories'));
    }

    public function create() {
        $product = new Product();
        return view('admin.products.create', compact('product'));
    }

    public function store(Request $request) {

        // Validate the form
        $request->validate([
            'name' => 'required',
            'price' => 'required',
            'description' => 'required',
            'image' => 'image|required'
        ]);

        // Upload the image
        if ($request->hasFile('image')) {
            $image = $request->image;
            $image->move('uploads', $image->getClientOriginalName());
        }

        // Save the data into database
        Product::create([
            'name' => $request->name,
            'price' => $request->price,
            'description' => $request->description,
            'image' => $request->image->getClientOriginalName()

        ]);

        // Sessions Message
        $request->session()->flash('msg','Your product has been added');

        // Redirect

        return redirect('admin/products/create');

    }

    public function edit($id) {
        $product = Product::find($id);
        return view('admin.products.edit', compact('product'));
    }

    public function update(Request $request, $id) {

        // Find the product
        $product = Product::find($id);
        // Validate The form
        $request->validate([
            'name' => 'required',
            'price' => 'required',
            'description' => 'required',
        ]);

//        // Check if there is any image
//        if ($request->hasFile('image')) {
//            // Check if the old image exists inside folder
//            if (file_exists(public_path('uploads/') . $product->image)) {
//                unlink(public_path('uploads/') . $product->image);
//            }
//
//            // Upload the new image
//            $image = $request->image;
//            $image->move('uploads', $image->getClientOriginalName());
//
//            $product->image = $request->image->getClientOriginalName();
//        }

        // Updating the product
        $product->update([
           'name' => $request->name,
            'price' => $request->price,
            'description' => $request->description,
        ]);

        // Store a message in session
        $request->session()->flash('msg', 'Product has been updated');

        // Redirect
        return redirect('admin/products');

    }

    public function show($id) {
        $product = Product::find($id);
        return view('admin.products.details', compact('product'));
    }

    public function destroy($id) {
        // Delete the product
        Product::destroy($id);

        // Store a message
        session()->flash('msg','Product has been deleted');

        // Redirect back
        return redirect('admin/products');


    }

    public function search(){
        $keyword = $_GET['keyword'];
        $products = Product::where('name','like', '%' . $keyword . '%')
            ->get();
        $category = Category::with('childrenCategories')->get();
        $categories = [];
        foreach ($category as $cat){

            $categories[]= $cat;
        }

        return view('admin.products.index', compact('products','categories'));

    }

    public function category($id){
        $products = Product::where('category',$id)
            ->orWhere('category1',$id)
            ->orWhere('category2',$id)
            ->where('available','Da')
            ->paginate(18);

        $category = Category::with('childrenCategories')->get();
        $categories = [];
        foreach ($category as $cat){

            $categories[]= $cat;
        }

        return view('admin.products.index', compact('products','categories'));

    }

    public function actionCreate(Request $request){
        $new_price = $request->price - ($request->price * ($request->discount / 100));
        Action::updateOrCreate([
            'product_id' => $request->id],[
            'name'=> $request->name,
            'price' =>  $new_price,
            'images' => $request->images,
            'description' => $request->description,

            'discount' => $request->discount
        ]);

        Product::where('id',$request->id)->update(['action_price'=>$new_price,'on_action'=>true]);

        session()->flash('msg','Akcija dodata');

        return redirect()->route('admin');
    }


    public function deleteAction($product_id){
        Action::where('product_id',$product_id)->delete();

        Product::where('id',$product_id)->update(['action_price'=>'0.00','on_action'=>false]);

        return redirect()->back();
    }

    public function actions(){

      $products = Action::all();

      return view('admin.products.actions',compact('products'));

    }

}

resources/views/admin/products/_fields.blade.php
<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
    {{ Form::label('product_name', 'Ime proizvoda') }}
    {{ Form::text('name',$product->name,['class'=>'form-control border-input','placeholder'=>'Macbook pro']) }}
    <span class="text-danger">{{ $errors->has('name') ? $errors->first('name') : '' }}</span>
</div>

<div class="form-group {{ $errors->has('price') ? 'has-error' : '' }}">
    {{ Form::label('price', 'Cena') }}
    {{ Form::text('price',$product->price,['class'=>'form-control border-input','placeholder'=>'2500 din.']) }}
    <span class="text-danger">{{ $errors->has('price') ? $errors->first('price') : '' }}</span>
</div>

<div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
    {{ Form::label('description', 'Opis') }}
    {{ Form::textarea('description',$product->description,['class'=>'form-control border-input','placeholder'=>'Opis']) }}
    <span class="text-danger">{{ $errors->has('description') ? $errors->first('description') : '' }}</span>
</div>

resources/views/admin/products/actions.blade.php
@extends('admin.layouts.master')

@section('page')
    Pogledaj proizvode
@endsection

@section('content')

    <div class="row">

        <div class="col-md-12">

            @include('admin.layouts.message')

                <div class="content table-responsive table-full-width">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Ime</th>
                            <th>Cena</th>
                            <th>Opis</th>
                            <th>Popust</th>
                            <th>Slika</th>
                            <th>Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($products as $product)
                            @if($product->name != "")
                                <tr>
                                    <td>{{ $product->name }}</td>
                                    <td>{{ $product->price }}</td>
                                    <td>{{ $product->description }}</td>
                                    <td>{{ $product->discount }} %</td>

                                @if(json_decode($product->images !== null ))
                                        @foreach(json_decode($product->images) as $image => $value)
                                            @if(is_array($value))
                                                <td><img class="img-thumbnail" src="{{$value[0]}}" alt="" style="width:50px;"></td>
                                            @else
                                                <td><img class="img-thumbnail" src="{{$value}}" alt="" style="width:50px;"></td>
                                            @endif
                                        @endforeach
                                    @endif
                                    <td>

                                        {{ Form::open(['route' => ['admin.action',$product->product_id], 'method'=>'DELETE']) }}
                                        {{ Form::button('<span class="fa fa-trash"></span>', ['type'=>'submit','class'=>'btn btn-danger btn-sm','onclick'=>'return confirm("Are you sure you want to delete this?")'])  }}
                                        {{ Form::close() }}

                                    </td>
                                </tr>
                            @endif
                        @endforeach
                        </tbody>
                    </table>
                    @if($products instanceof \Illuminate\Pagination\LengthAwarePaginator )
                        <div class="d-flex justify-content-center">
                            {{ $products->links() }}
                        </div>

                    @endif
                </div>
            </div>
        </div>


    </div>


@endsection

resources/views/admin/products/bestseller.blade.php
@extends('admin.layouts.master')

@section('page')
    Pogledaj proizvode
@endsection

@section('content')

    <div class="row">

        <div class="col-md-12">
                <div class="content table-responsive table-full-width">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Ime</th>
                            <th>Cena</th>
                            <th>Opis</th>
                            <th>Slika</th>
                            <th>Akcija</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($products as $product)
                            @if($product->name != "")
                                <tr>
                                    <td>{{ $product->id }}</td>
                                    <td>{{ $product->name }}</td>
                                    <td>{{ $product->price }}</td>
                                    <td>{{ $product->description }}</td>
                                    @if(json_decode($product->images !== null ))
                                        @foreach(json_decode($product->images) as $image => $value)
                                            @if(is_array($value))
                                                <td><img class="img-thumbnail" src="{{$value[0]}}" alt="" style="width:50px;"></td>
                                            @else
                                                <td><img class="img-thumbnail" src="{{$value}}" alt="" style="width:50px;"></td>
                                            @endif
                                        @endforeach
                                    @endif
                                    <td>

                                        {{ Form::open(['route' => ['bestseller.destroy', $product->code], 'method'=>'DELETE']) }}
                                        {{ Form::button('<span class="fa fa-trash"></span>', ['type'=>'submit','class'=>'btn btn-danger btn-sm','onclick'=>'return confirm("Are you sure you want to delete this?")'])  }}
                                        {{ Form::close() }}

                                    </td>
                                </tr>
                            @endif
                        @endforeach
                        </tbody>
                    </table>
                    @if($products instanceof \Illuminate\Pagination\LengthAwarePaginator )
                        <div class="d-flex justify-content-center">
                            {{ $products->links() }}
                        </div>

                    @endif
                </div>
            </div>
        </div>


    </div>


@endsection

resources/views/admin/products/create.blade.php
@extends('admin.layouts.master')

@section('page')
    Dodaj proizvod
@endsection

@section('content')

    <div class="row">
        <div class="col-lg-10 col-md-10">
            @include('admin.layouts.message')
            <div class="card">
                <div class="header">
                    <h4 class="title">Dodaj proizvod</h4>
                </div>

                <div class="content">
                    {!! Form::open(['url' => 'admin/products', 'files'=>'true']) !!}
                    <div class="row">
                        <div class="col-md-12">

                            @include('admin.products._fields')

                            <div class="form-group">
                                {{ Form::submit('Dodaj proizvod', ['class'=>'btn btn-primary']) }}
                            </div>

                        </div>

                    </div>


                    <div class="clearfix"></div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/admin/products/details.blade.php
@extends('admin.layouts.master')

@section('page')
    Dodaj akciju
@endsection

@section('content')

    <div class="row">

        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Dodaj akciju</h4>
                </div>
                <div class="content table-responsive table-full-width">
                    {!! Form::open(['url' => ['admin/action'], 'files'=>'true', 'method'=>'post']) !!}

                    <table class="table table-striped">
                        <tbody>

                        <tr>
                            <td>Ime</td>
                            <td>Opis</td>
                            <td>Cena</td>
                            <td>Popust(u procentima)</td>
                        </tr>
                        <tr>
                            <td style="display:none;">{!! Form::text('id', $product->id ) !!}</td>
                            <td>{!! Form::text('name', $product->name, ['class' => 'form-control', 'size' => '20']) !!}</td>
                            <td>{!! Form::text('description', $product->description, ['class' => 'form-control', 'size' => '20']) !!}</td>
                            <td>{!! Form::text('price', $product->price, ['class' => 'form-control', 'size' => '1']) !!}</td>
                            <td>{!! Form::text('discount', '', ['class' => 'form-control', 'size' => '1']) !!}</td>
                            <td style="display:none;">{!! Form::text('images', $product->images) !!}</td>
                        </tbody>

                    </table>
                    <div class="form-group">
                        {{ Form::submit('Dodaj akciju', ['class'=>'btn btn-primary']) }}
                    </div>
                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/products/edit.blade.php
@extends('admin.layouts.master')

@section('page')
    Izmeni proizvod
@endsection

@section('content')

    <div class="row">
        <div class="col-lg-10 col-md-10">
            @include('admin.layouts.message')
            <div class="card">
                <div class="header">
                    <h4 class="title">Izmeni proizvod</h4>
                </div>

                <div class="content">
                    {!! Form::open(['url' => ['admin/products', $product->id], 'files'=>'true', 'method'=>'put']) !!}
                    <div class="row">
                        <div class="col-md-12">

                            @include('admin.products._fields')

                            <div class="form-group">
                                {{ Form::submit('Update Product', ['class'=>'btn btn-primary']) }}
                            </div>

                        </div>

                    </div>


                    <div class="clearfix"></div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/admin/products/index.blade.php
@extends('admin.layouts.master')

@section('page')
    Pogledaj proizvode
@endsection

@section('content')

    <div class="row">

        <div class="col-md-12">

            @include('admin.layouts.message')

            <div class="card">
                <div class="header">
                    <h4 class="title">Proizvodi</h4>
                    <p class="category">Lista proizvoda</p>
                    <div>
                        <form class="input-group" action="{{ url('admin/search') }}" method="GET">
                            <input type="text" name="keyword" class="form-control" placeholder="Pretrazi proizvod" minlength="3">
                            <div class="input-group-append">
                                <button class="btn btn-secondary" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-3 dropdown">

                        <a href="#" class="btn dropdown-toggle" data-toggle="dropdown">
                            Kategorije
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu"> @foreach($categories as $category)
                                @if($category->parent_id == 0 && !empty($category->name))
                                    <button><a class="dropdown-item" type="button"
                                               href="{{url('admin/category',$category->name)}}">{{$category->name}}</a></button>
                                @endif
                            @endforeach
                        </ul>
                    </div>
                </div>
                <div class="content table-responsive table-full-width">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Ime</th>
                            <th>Cena</th>
                            <th>Opis</th>
                            <th>Slika</th>
                            <th>Akcija</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($products as $product)
                            @if($product->name != "")
                            <tr>
                                <td>{{ $product->id }}</td>
                                <td>{{ $product->name }}</td>
                                <td>{{ $product->price }}</td>
                                <td>{{ $product->description }}</td>
                                @if(json_decode($product->images !== null ))
                                    @foreach(json_decode($product->images) as $image => $value)
                                        @if(is_array($value))
                                            <td><img class="img-thumbnail" src="{{$value[0]}}" alt="" style="width:50px;"></td>
                                        @else
                                            <td><img class="img-thumbnail" src="{{$value}}" alt="" style="width:50px;"></td>
                                        @endif
                                    @endforeach
                                @endif
                                <td>

                                    {{ Form::open(['route' => ['products.destroy', $product->id], 'method'=>'DELETE']) }}
                                        {{ Form::button('<span class="fa fa-trash"></span>', ['type'=>'submit','class'=>'btn btn-danger btn-sm','onclick'=>'return confirm("Are you sure you want to delete this?")'])  }}
                                        {{ link_to_route('products.edit','', $product->id, ['class' => 'btn btn-info btn-sm ti-pencil']) }}
                                        {{ link_to_route('products.show','', $product->id, ['class' => 'btn btn-primary btn-sm ti-list']) }}
                                    {{ Form::close() }}
                                    {{ Form::open(['route' => ['makeBestseller', $product->code], 'method'=>'POST']) }}
                                    {{ Form::button('<i class="fa fa-plus"></i>', ['type'=>'submit','class'=>'btn btn-primary btn-sm'])  }}
                                    {{ Form::close() }}


                                </td>
                            </tr>
                            @endif
                            @endforeach
                        </tbody>
                    </table>
                    @if($products instanceof \Illuminate\Pagination\LengthAwarePaginator )
                        <div class="d-flex justify-content-center">
                            {{ $products->links() }}
                        </div>

                    @endif
                </div>
            </div>
        </div>


    </div>


@endsection